// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ythjahhxnwggzzfzwhal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aGphaGh4bndnZ3p6Znp3aGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDMwOTAsImV4cCI6MjA1OTMxOTA5MH0.KvFyfVsSHQ0Z6vcd4UljV1AuxrvuWEIwfo9BrmunkyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);